### ISSUE TITLE
I don't think this works at all

### ISSUE THREAD

**Issue by ungoldman** [koopjs/koop-ckan#11]
@timwis were you able to get results when working with this module? I'm testing locally to try to get some real tests in for #10 and suspecting that it's completely broken.

**Comment by ngoldman** [comment]
None of the links in the [examples](https://github.com/koopjs/koop-ckan#examples) section of the readme work either.

:disappointed:

**Comment by timwis** [comment]
Hah, yes I was able to get results, but I often got that "unable to retrieve data" error and assumed I set it up wrong. I worked with [heart healthy screening sites](https://www.opendataphilly.org/dataset/heart-healthy-screening-sites), which seems to work on both your demo server and my local server:

http://koop.dc.esri.com/ckan/phil/heart-healthy-screening-sites
