### ISSUE TITLE
Ckan Provider Failing

### ISSUE THREAD

**Issue by dmartine** [koopjs/koop-ckan#5]
# Using version Ckan provider 0.0.8

1.  Installed koop sample app with PostgreSQL 9.4 and added extension for postgis.
2.  Registered provider for data.hdx.rwlabs.org.
3. Used http://localhost:1337/ckan/rwlabs/ourairports-ind and received TypeError: Cannot call method 'forEach' of undefined at Object.exports.fromCSV.
![ckanerrors](https://cloud.githubusercontent.com/assets/2925134/7497919/328a508c-f3d2-11e4-926c-dd1daa4f7c82.PNG)

I noticed http://koop.dc.esri.com/ckan/rwlabs/ourairports-ind works. Is that running a different version of ckan?  Also tried on @jgravois machine and was able to produce the same results.

**Comment by jgravois** [comment]
on my machine, this shows up in the PostGres logs, even though a call to `http://localhost:1337/ckan` returns the appropriate serviceId
```
STATEMENT:  select count(*) as count from "ckan:services"
ERROR:  relation "ckan:services" does not exist at character 31
```

**Comment by chelm** [comment]
@jgravios You might need to register a ckan instance first. I think there's an issue with this provider where it doesn't handle the case when no providers are registered yet. 

I get the same error that @dmartine reports and it due to getting a 404 at  https://data.hdx.rwlabs.org/ourairports-ind - we'll need to add support for catching 404s from CKAN

**Comment by jgravois** [comment]
i've definitely got the ckan instance registered.  how is [koop.dc.esri.com](http://koop.dc.esri.com/ckan/rwlabs/ourairports-ind) already handling this 404?

**Comment by chelm** [comment]
@jgravois so the reason why koop.dc handles that one is because its cached, as soon as its dropped that link will break.

**Comment by jgravois** [comment]
:bulb: thx @chelm

**Comment by chelm** [comment]
@jgravois @dmartine PR #6

**Comment by dmfenton** [comment]
Going to handle this in issue #8
